steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/united-planet-412315/harshith100922585/harshithimage:${COMMIT_SHA}', '.']
  # Push the Docker image to the artifact registry!
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/united-planet-412315/harshith100922585/harshithimage:${COMMIT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud run deploy nodejs-app \
          --image=us-central1-docker.pkg.dev/united-planet-412315/harshith100922585/harshithimage:${COMMIT_SHA} \
          --platform=managed \
          --region=us-central1 \
          --port=3000 \
          --allow-unauthenticated
 
options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  # defaultLogsBucket: 'gs://your-build-logs-bucket' # Replace with your build logs bucket
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
 
images:
# Store images in Google Artifact Registry
  - us-central1-docker.pkg.dev/united-planet-412315/harshith100922585/harshithimage:${COMMIT_SHA}
